project:
  type: website
  resources: 
    - "*.ggb"  
website:
  title: "Códigos y Criptografía"
  search: false
  sidebar: 
    style: "docked"
    footer: Hecho con [Quarto](https://quarto.org/)
    contents:
    - section: Inicio
      contents: index.qmd
    - section: Teoría
      contents: 
        - Codigos_Lineales.qmd
    - section: Scripts
      contents: 
        - Tutorial.ipynb
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true